name: verifiers
on: [push, pull_request, workflow_dispatch]

# Run many verifiers on metamath files.
# We *primarily* check set.mm and iset.mm, but we also run some checks on
# other files (in particular on some HTML files).
#
# Only one verifier is necessary, but using multiple verifiers counters
# the risk that a verifier might have a defect in its implementation.
# With 4 verifiers, all 4 would have to have a defect involving an
# invalid theorem for that invalid theorem to be accepted as valid.
# This is unlikely, because the verifiers are written by different people
# in different languages.  This can be considered extreme peer review, where
# every reviewer is separately checking each step.
# Some of these verifiers also check for style,
# so using multiple verifiers can also detect many different style problems.
#
# Note that one of the checks is scripts/verify.
#
# We report an error if the list of "discouraged" results is unexpected;
# this makes it easy to detect changes (which can then be specially reviewed).
# To regenerate the "discouraged" file, you can run scripts/gen-discouraged
#
# We typically rewrap the file using scripts/rewrap.

# TODO: We aren't caching many old results; add caches
# (e.g., of unchanged compiled programs) to speed things further.

# In each job we download, build, install, and run a verifier.
# NOTE: We generally install programs in $HOME/bin, so ensure that's on the
# PATH (usually it is on any non-Windows system).

jobs:
  ###########################################################
  skip_dups:
    name: Check for duplicate jobs to avoid duplication
    # continue-on-error: true # Uncomment once integration is finished
    runs-on: ubuntu-latest
    # Map a step output to a job output
    outputs:
      should_skip: ${{ steps.skip_check.outputs.should_skip }}
    steps:
      - id: skip_check
        uses: fkirc/skip-duplicate-actions@master
        with:
          github_token: ${{ github.token }}
          paths_ignore: '["**/README.md", "**/docs/**"]'

  ###########################################################
  mmj2:
    name: Verify using mmj2 (Java verifier by Mel L. O'Cat and Mario Carneiro)
    runs-on: ubuntu-latest
    needs: skip_dups
    if: ${{ needs.skip_dups.outputs.should_skip != 'true' }}
    steps:
      - uses: actions/checkout@v3
      # See: https://github.com/actions/setup-java
      - uses: actions/setup-java@v3
        with:
          distribution: 'zulu' # ('temurin', 'zulu', ...) - required field
          java-version: '11' # The JDK version to make available on the path.
          # java-package: jdk # (jdk, jre, jdk+fx, or jre+fx) - defaults to jdk
          # architecture: x64 # (x86, x64, armv7, aarch64, or ppc64le) - default value derived from the runner machine
      - run: wget -N https://github.com/digama0/mmj2/raw/master/mmj2jar/mmj2.jar
      - run: mkdir macros
      - run: wget -O macros/definitionCheck.js https://github.com/digama0/mmj2/raw/master/mmj2jar/macros/definitionCheck.js
      - run: wget -O macros/init.js https://github.com/digama0/mmj2/raw/master/mmj2jar/macros/init.js
      - run: wget -O macros/showDiscouraged.js https://github.com/digama0/mmj2/raw/master/mmj2jar/macros/showDiscouraged.js
      # Do extra checking and generate the '*discouraged.new' file
      # (the 'printf' lets us insert multiple lines).
      # We use setparser to check that definitions don't create
      # syntax ambiguities
      - run: scripts/verify-mmj2 --setparser 'mmj.verify.LRParser' --extra "$(printf 'RunMacro,definitionCheck,ax-*,df-bi,df-clab,df-cleq,df-clel\nRunMacro,showDiscouraged,discouraged.new')" set.mm
      - run: echo 'Checking discouraged file:' && diff -U 0 discouraged discouraged.new